spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products #this is the address of api-gateway
    # why use api-gateway?
    # we might have to run multiple instances of product-service for load balancing and fault tolerance,then api-gateway
    # will route the request to one of the instances of product-service