spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/product
        username: postgres
        password: 123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
          ddl-auto: validate
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
        enabled: true
        baseline-description: "init"
        baseline-version: 0
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
    application:
        name: product-service
    config:
        import: optional:configserver:http://localhost:8888
server:
    port: 8050