spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      username: notification_user
      password: notification_pass
      host: localhost
      port: 27017
      database: notification
      authentication-database: notification
server:
  port: 8030
