create table category (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
    description text,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp
);

create table product (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
    description text,
    price decimal(10, 2) not null,
    quantity double precision not null,
    category_id integer
        constraint foreign_key_constraint references category(id),
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp
);